In [1]:
import pandas as pd
import numpy as np

#censuslink url https://factfinder.census.gov/faces/tableservices/jsf/pages/productview.xhtml?src=bkmk
#state url https://www.factmonster.com/us/postal-information/state-abbreviations-and-state-postal-codes

In [2]:
url = 'https://www.numbeo.com/quality-of-life/region_rankings_current.jsp?region=021'

In [3]:
#scrape and read as pandas df
tables = pd.read_html(url)
tables

[    0                                                  1
 0 NaN  What are you looking for? Cost of Living Crime...,     0      1
 0 NaN  Tweet,     Rank                               City  Quality of Life Index  \
 0    NaN         Raleigh, NC, United States                 231.41
 1    NaN         Madison, WI, United States                 207.65
 2    NaN          Dallas, TX, United States                 201.17
 3    NaN       Charlotte, NC, United States                 199.48
 4    NaN          Austin, TX, United States                 198.47
 5    NaN        Columbus, OH, United States                 197.25
 6    NaN                     Ottawa, Canada                 196.03
 7    NaN        San Jose, CA, United States                 194.75
 8    NaN                   Victoria, Canada                 193.88
 9    NaN       San Diego, CA, United States                 191.72
 10   NaN        Richmond, VA, United States                 191.00
 11   NaN         Seattle, WA, United States                 189.69
 12   NaN        Portland, OR, United States                 188.22
 13   NaN     San Antonio, TX, United States                 188.19
 14   NaN                Quebec City, Canada                 187.92
 15   NaN    Jacksonville, FL, United States                 187.31
 16   NaN                    Calgary, Canada                 186.95
 17   NaN     Kansas City, MO, United States                 184.19
 18   NaN     Saint Louis, MO, United States                 182.10
 19   NaN      Sacramento, CA, United States                 182.04
 20   NaN          Boston, MA, United States                 181.72
 21   NaN      Cincinnati, OH, United States                 180.74
 22   NaN           Tampa, FL, United States                 180.70
 23   NaN       Nashville, TN, United States                 180.36
 24   NaN     Minneapolis, MN, United States                 179.88
 25   NaN         Spokane, WA, United States                 178.15
 26   NaN         Oakland, CA, United States                 177.31
 27   NaN   San Francisco, CA, United States                 177.30
 28   NaN                  Vancouver, Canada                 175.16
 29   NaN                Mississauga, Canada                 174.97
 ..   ...                                ...                    ...
 31   NaN                   Edmonton, Canada                 174.93
 32   NaN         Atlanta, GA, United States                 174.72
 33   NaN                    Kelowna, Canada                 174.63
 34   NaN     Albuquerque, NM, United States                 174.24
 35   NaN  Salt Lake City, UT, United States                 174.18
 36   NaN         Houston, TX, United States                 173.57
 37   NaN          Tucson, AZ, United States                 173.44
 38   NaN       Anchorage, AK, United States                 171.27
 39   NaN      Washington, DC, United States                 170.65
 40   NaN                    Halifax, Canada                 169.75
 41   NaN          Denver, CO, United States                 169.01
 42   NaN       Cleveland, OH, United States                 167.97
 43   NaN         Orlando, FL, United States                 167.96
 44   NaN                   Montreal, Canada                 167.81
 45   NaN       Baltimore, MD, United States                 167.05
 46   NaN        Honolulu, HI, United States                 165.80
 47   NaN                   Hamilton, Canada                 164.71
 48   NaN    Indianapolis, IN, United States                 164.66
 49   NaN       Las Vegas, NV, United States                 163.60
 50   NaN         Phoenix, AZ, United States                 159.29
 51   NaN         Chicago, IL, United States                 158.15
 52   NaN     Los Angeles, CA, United States                 157.97
 53   NaN       Milwaukee, WI, United States                 155.87
 54   NaN           Miami, FL, United States                 153.42
 55   NaN    Philadelphia, PA, United States                 151.11
 56   NaN                    Toronto, Canada                 149.79
 57   NaN                     Regina, Canada                 148.46
 58   NaN                   Winnipeg, Canada                 147.73
 59   NaN        New York, NY, United States                 141.03
 60   NaN         Detroit, MI, United States                 130.08

     Purchasing Power Index  Safety Index  Health Care Index  \
 0                   189.67         70.73              78.10
 1                   135.21         72.77              81.94
 2                   185.61         51.39              67.63
 3                   148.02         56.62              75.66
 4                   155.55         65.05              70.89
 5                   133.74         57.90              75.19
 6                   132.19         75.60              74.99
 7                   173.72         57.44              68.83
 8                    95.50         69.40              71.83
 9                   136.24         63.00              71.33
 10                  116.41         57.43              73.64
 11                  142.76         54.32              72.74
 12                  129.18         52.84              71.17
 13                  135.23         53.64              71.98
 14                  129.44         84.40              67.31
 15                  136.36         42.33              72.56
 16                  140.00         68.27              76.65
 17                  131.32         41.08              77.26
 18                  134.85         32.44              81.23
 19                  128.14         50.19              70.51
 20                  122.93         66.06              75.90
 21                  129.22         51.18              68.50
 22                  121.15         50.49              66.69
 23                  140.97         53.01              62.45
 24                  125.83         50.28              79.80
 25                  107.07         48.00              62.49
 26                  126.27         35.86              77.73
 27                  140.85         51.02              71.42
 28                   96.97         64.25              74.10
 29                  115.22         56.59              67.03
 ..                     ...           ...                ...
 31                  123.55         57.74              78.59
 32                  154.57         37.32              64.48
 33                  104.33         51.57              71.05
 34                  115.89         29.95              69.11
 35                  138.87         73.67              71.14
 36                  155.10         38.76              71.69
 37                  111.07         47.98              59.63
 38                  130.57         41.12              59.85
 39                  137.64         43.28              69.02
 40                   94.28         58.83              71.54
 41                  122.12         58.56              71.48
 42                  105.92         35.31              83.06
 43                  105.03         45.06              62.78
 44                  110.60         69.10              63.93
 45                  125.12         28.92              80.05
 46                  101.44         55.63              70.69
 47                  121.42         50.02              82.69
 48                  113.29         43.27              68.80
 49                  142.80         45.04              55.26
 50                  139.11         47.06              66.01
 51                  130.96         35.30              68.48
 52                  123.33         59.31              66.24
 53                   98.77         34.41              65.62
 54                   92.96         48.00              63.85
 55                  100.77         40.49              72.25
 56                   86.35         63.86              75.42
 57                  104.69         44.58              67.86
 58                  107.32         44.24              67.93
 59                  100.00         57.64              63.95
 60                   90.15         28.06              65.44

     Cost of Living Index  Property Price to Income Ratio  \
 0                  72.77                            2.03
 1                  65.44                            3.22
 2                  66.75                            1.98
 3                  77.14                            2.26
 4                  69.91                            3.77
 5                  68.70                            2.16
 6                  68.14                            4.54
 7                  80.85                            5.89
 8                  69.30                            7.64
 9                  73.18                            5.80
 10                 68.52                            3.17
 11                 85.25                            5.87
 12                 77.98                            4.47
 13                 65.71                            2.26
 14                 64.23                            3.57
 15                 69.04                            1.99
 16                 69.13                            4.77
 17                 69.01                            2.16
 18                 67.54                            2.44
 19                 77.44                            3.69
 20                 86.87                            7.92
 21                 64.97                            2.31
 22                 69.95                            3.09
 23                 68.82                            2.89
 24                 76.50                            3.10
 25                 73.64                            3.15
 26                 85.02                            6.25
 27                 89.67                            8.69
 28                 71.09                           14.36
 29                 66.50                            7.68
 ..                   ...                             ...
 31                 69.57                            3.83
 32                 71.59                            2.76
 33                 66.49                            5.40
 34                 66.73                            3.12
 35                 64.21                            3.77
 36                 64.65                            2.04
 37                 71.54                            2.63
 38                 92.69                            2.61
 39                 90.92                            4.28
 40                 68.86                            6.95
 41                 74.59                            4.81
 42                 72.71                            1.41
 43                 70.76                            3.13
 44                 64.61                            6.86
 45                 75.74                            2.52
 46                 90.80                            8.77
 47                 60.37                            6.25
 48                 68.33                            2.33
 49                 68.35                            2.50
 50                 66.80                            2.87
 51                 79.39                            3.60
 52                 77.66                            7.26
 53                 70.94                            3.19
 54                 78.11                            5.47
 55                 85.28                            3.61
 56                 81.31                           13.52
 57                 68.33                            4.80
 58                 60.79                            4.92
 59                100.00                           11.05
 60                 64.70                            1.67

     Traffic Commute Time Index  Pollution Index  Climate Index
 0                        33.87            19.17          83.88
 1                        23.73            16.77          51.64
 2                        35.30            40.20          81.85
 3                        38.27            25.82          84.05
 4                        34.54            35.93          82.08
 5                        26.16            25.39          71.29
 6                        32.73            17.61          44.46
 7                        35.75            46.48          95.53
 8                        27.50            15.41          92.52
 9                        35.42            36.51          97.08
 10                       20.10            31.14          81.27
 11                       42.71            27.73          91.73
 12                       33.24            28.96          89.56
 13                       28.08            38.25          80.58
 14                       28.61            37.02          47.98
 15                       34.46            30.85          87.81
 16                       32.35            25.52          33.09
 17                       25.65            34.39          75.08
 18                       27.53            33.77          74.75
 19                       25.97            42.46          90.64
 20                       43.59            24.53          71.73
 21                       24.52            40.93          73.24
 22                       36.55            29.32          84.67
 23                       37.56            39.96          83.02
 24                       35.53            23.23          49.46
 25                       24.16            20.17          67.12
 26                       32.04            35.38          96.40
 27                       45.90            37.38          97.26
 28                       36.39            24.18          91.15
 29                       34.06            21.66          58.72
 ..                         ...              ...            ...
 31                       30.38            29.28          32.11
 32                       43.24            44.89          89.73
 33                       30.91            20.53          59.65
 34                       25.77            21.62          67.06
 35                       34.88            61.80          66.52
 36                       41.45            53.70          85.53
 37                       30.38            27.12          72.66
 38                       30.95            17.96          41.61
 39                       41.45            40.14          81.62
 40                       30.00            25.24          58.99
 41                       34.73            40.25          56.28
 42                       34.48            35.59          73.11
 43                       36.88            33.18          87.23
 44                       39.56            31.35          52.37
 45                       32.12            45.61          81.24
 46                       40.97            36.47          95.33
 47                       35.81            48.15          61.06
 48                       30.83            42.82          69.92
 49                       27.54            51.27          57.40
 50                       32.19            57.85          53.76
 51                       40.86            44.02          66.11
 52                       47.36            60.96          95.50
 53                       30.67            32.68          60.96
 54                       43.07            40.59          85.69
 55                       40.38            48.01          77.98
 56                       43.49            37.85          65.35
 57                       17.27            41.01          14.28
 58                       32.10            38.50          24.67
 59                       43.26            55.88          79.66
 60                       47.35            54.56          66.03

 [61 rows x 11 columns]]

In [4]:
quality_df = tables[2]
len(quality_df['Rank'])

61

In [5]:
# populate rank starting with 1
quality_df['Rank'] = [x for x in range(1,len(quality_df)+1)]

In [6]:
#show clean rank
quality_df.head()

,Rank,City,Quality of Life Index,Purchasing Power Index,Safety Index,Health Care Index,Cost of Living Index,Property Price to Income Ratio,Traffic Commute Time Index,Pollution Index,Climate Index
0,1,"Raleigh, NC, United States",231.41,189.67,70.73,78.10,72.77,2.03,33.87,19.17,83.88
1,2,"Madison, WI, United States",207.65,135.21,72.77,81.94,65.44,3.22,23.73,16.77,51.64
2,3,"Dallas, TX, United States",201.17,185.61,51.39,67.63,66.75,1.98,35.30,40.20,81.85
3,4,"Charlotte, NC, United States",199.48,148.02,56.62,75.66,77.14,2.26,38.27,25.82,84.05
4,5,"Austin, TX, United States",198.47,155.55,65.05,70.89,69.91,3.77,34.54,35.93,82.08

In [7]:
#Find country and populate
quality_df['Country'] = ''
quality_df.loc[quality_df['City'].str.contains('Canada', case=False), 'Country'] = 'Canada'
quality_df.loc[quality_df['City'].str.contains('United States', case=False), 'Country'] = 'United States'
quality_df

,Rank,City,Quality of Life Index,Purchasing Power Index,Safety Index,Health Care Index,Cost of Living Index,Property Price to Income Ratio,Traffic Commute Time Index,Pollution Index,Climate Index,Country
0,1,"Raleigh, NC, United States",231.41,189.67,70.73,78.10,72.77,2.03,33.87,19.17,83.88,United States
1,2,"Madison, WI, United States",207.65,135.21,72.77,81.94,65.44,3.22,23.73,16.77,51.64,United States
2,3,"Dallas, TX, United States",201.17,185.61,51.39,67.63,66.75,1.98,35.30,40.20,81.85,United States
3,4,"Charlotte, NC, United States",199.48,148.02,56.62,75.66,77.14,2.26,38.27,25.82,84.05,United States
4,5,"Austin, TX, United States",198.47,155.55,65.05,70.89,69.91,3.77,34.54,35.93,82.08,United States
5,6,"Columbus, OH, United States",197.25,133.74,57.90,75.19,68.70,2.16,26.16,25.39,71.29,United States
6,7,"Ottawa, Canada",196.03,132.19,75.60,74.99,68.14,4.54,32.73,17.61,44.46,Canada
7,8,"San Jose, CA, United States",194.75,173.72,57.44,68.83,80.85,5.89,35.75,46.48,95.53,United States
8,9,"Victoria, Canada",193.88,95.50,69.40,71.83,69.30,7.64,27.50,15.41,92.52,Canada
9,10,"San Diego, CA, United States",191.72,136.24,63.00,71.33,73.18,5.80,35.42,36.51,97.08,United States
10,11,"Richmond, VA, United States",191.00,116.41,57.43,73.64,68.52,3.17,20.10,31.14,81.27,United States
11,12,"Seattle, WA, United States",189.69,142.76,54.32,72.74,85.25,5.87,42.71,27.73,91.73,United States
12,13,"Portland, OR, United States",188.22,129.18,52.84,71.17,77.98,4.47,33.24,28.96,89.56,United States
13,14,"San Antonio, TX, United States",188.19,135.23,53.64,71.98,65.71,2.26,28.08,38.25,80.58,United States
14,15,"Quebec City, Canada",187.92,129.44,84.40,67.31,64.23,3.57,28.61,37.02,47.98,Canada
15,16,"Jacksonville, FL, United States",187.31,136.36,42.33,72.56,69.04,1.99,34.46,30.85,87.81,United States
16,17,"Calgary, Canada",186.95,140.00,68.27,76.65,69.13,4.77,32.35,25.52,33.09,Canada
17,18,"Kansas City, MO, United States",184.19,131.32,41.08,77.26,69.01,2.16,25.65,34.39,75.08,United States
18,19,"Saint Louis, MO, United States",182.10,134.85,32.44,81.23,67.54,2.44,27.53,33.77,74.75,United States
19,20,"Sacramento, CA, United States",182.04,128.14,50.19,70.51,77.44,3.69,25.97,42.46,90.64,United States
20,21,"Boston, MA, United States",181.72,122.93,66.06,75.90,86.87,7.92,43.59,24.53,71.73,United States
21,22,"Cincinnati, OH, United States",180.74,129.22,51.18,68.50,64.97,2.31,24.52,40.93,73.24,United States
22,23,"Tampa, FL, United States",180.70,121.15,50.49,66.69,69.95,3.09,36.55,29.32,84.67,United States
23,24,"Nashville, TN, United States",180.36,140.97,53.01,62.45,68.82,2.89,37.56,39.96,83.02,United States
24,25,"Minneapolis, MN, United States",179.88,125.83,50.28,79.80,76.50,3.10,35.53,23.23,49.46,United States
25,26,"Spokane, WA, United States",178.15,107.07,48.00,62.49,73.64,3.15,24.16,20.17,67.12,United States
26,27,"Oakland, CA, United States",177.31,126.27,35.86,77.73,85.02,6.25,32.04,35.38,96.40,United States
27,28,"San Francisco, CA, United States",177.30,140.85,51.02,71.42,89.67,8.69,45.90,37.38,97.26,United States
28,29,"Vancouver, Canada",175.16,96.97,64.25,74.10,71.09,14.36,36.39,24.18,91.15,Canada
29,30,"Mississauga, Canada",174.97,115.22,56.59,67.03,66.50,7.68,34.06,21.66,58.72,Canada
...,...,...,...,...,...,...,...,...,...,...,...,...
31,32,"Edmonton, Canada",174.93,123.55,57.74,78.59,69.57,3.83,30.38,29.28,32.11,Canada
32,33,"Atlanta, GA, United States",174.72,154.57,37.32,64.48,71.59,2.76,43.24,44.89,89.73,United States
33,34,"Kelowna, Canada",174.63,104.33,51.57,71.05,66.49,5.40,30.91,20.53,59.65,Canada
34,35,"Albuquerque, NM, United States",174.24,115.89,29.95,69.11,66.73,3.12,25.77,21.62,67.06,United States
35,36,"Salt Lake City, UT, United States",174.18,138.87,73.67,71.14,64.21,3.77,34.88,61.80,66.52,United States
36,37,"Houston, TX, United States",173.57,155.10,38.76,71.69,64.65,2.04,41.45,53.70,85.53,United States
37,38,"Tucson, AZ, United States",173.44,111.07,47.98,59.63,71.54,2.63,30.38,27.12,72.66,United States
38,39,"Anchorage, AK, United States",171.27,130.57,41.12,59.85,92.69,2.61,30.95,17.96,41.61,United States
39,40,"Washington, DC, United States",170.65,137.64,43.28,69.02,90.92,4.28,41.45,40.14,81.62,United States
40,41,"Halifax, Canada",169.75,94.28,58.83,71.54,68.86,6.95,30.00,25.24,58.99,Canada
41,42,"Denver, CO, United States",169.01,122.12,58.56,71.48,74.59,4.81,34.73,40.25,56.28,United States
42,43,"Cleveland, OH, United States",167.97,105.92,35.31,83.06,72.71,1.41,34.48,35.59,73.11,United States
43,44,"Orlando, FL, United States",167.96,105.03,45.06,62.78,70.76,3.13,36.88,33.18,87.23,United States
44,45,"Montreal, Canada",167.81,110.60,69.10,63.93,64.61,6.86,39.56,31.35,52.37,Canada
45,46,"Baltimore, MD, United States",167.05,125.12,28.92,80.05,75.74,2.52,32.12,45.61,81.24,United States
46,47,"Honolulu, HI, United States",165.80,101.44,55.63,70.69,90.80,8.77,40.97,36.47,95.33,United States
47,48,"Hamilton, Canada",164.71,121.42,50.02,82.69,60.37,6.25,35.81,48.15,61.06,Canada
48,49,"Indianapolis, IN, United States",164.66,113.29,43.27,68.80,68.33,2.33,30.83,42.82,69.92,United States
49,50,"Las Vegas, NV, United States",163.60,142.80,45.04,55.26,68.35,2.50,27.54,51.27,57.40,United States
50,51,"Phoenix, AZ, United States",159.29,139.11,47.06,66.01,66.80,2.87,32.19,57.85,53.76,United States
51,52,"Chicago, IL, United States",158.15,130.96,35.30,68.48,79.39,3.60,40.86,44.02,66.11,United States
52,53,"Los Angeles, CA, United States",157.97,123.33,59.31,66.24,77.66,7.26,47.36,60.96,95.50,United States
53,54,"Milwaukee, WI, United States",155.87,98.77,34.41,65.62,70.94,3.19,30.67,32.68,60.96,United States
54,55,"Miami, FL, United States",153.42,92.96,48.00,63.85,78.11,5.47,43.07,40.59,85.69,United States
55,56,"Philadelphia, PA, United States",151.11,100.77,40.49,72.25,85.28,3.61,40.38,48.01,77.98,United States
56,57,"Toronto, Canada",149.79,86.35,63.86,75.42,81.31,13.52,43.49,37.85,65.35,Canada
57,58,"Regina, Canada",148.46,104.69,44.58,67.86,68.33,4.80,17.27,41.01,14.28,Canada
58,59,"Winnipeg, Canada",147.73,107.32,44.24,67.93,60.79,4.92,32.10,38.50,24.67,Canada
59,60,"New York, NY, United States",141.03,100.00,57.64,63.95,100.00,11.05,43.26,55.88,79.66,United States
60,61,"Detroit, MI, United States",130.08,90.15,28.06,65.44,64.70,1.67,47.35,54.56,66.03,United States

In [8]:
#Limit only where Country = United States
quality_US = quality_df[quality_df['Country'] == 'United States'].copy()
quality_US

,Rank,City,Quality of Life Index,Purchasing Power Index,Safety Index,Health Care Index,Cost of Living Index,Property Price to Income Ratio,Traffic Commute Time Index,Pollution Index,Climate Index,Country
0,1,"Raleigh, NC, United States",231.41,189.67,70.73,78.10,72.77,2.03,33.87,19.17,83.88,United States
1,2,"Madison, WI, United States",207.65,135.21,72.77,81.94,65.44,3.22,23.73,16.77,51.64,United States
2,3,"Dallas, TX, United States",201.17,185.61,51.39,67.63,66.75,1.98,35.30,40.20,81.85,United States
3,4,"Charlotte, NC, United States",199.48,148.02,56.62,75.66,77.14,2.26,38.27,25.82,84.05,United States
4,5,"Austin, TX, United States",198.47,155.55,65.05,70.89,69.91,3.77,34.54,35.93,82.08,United States
5,6,"Columbus, OH, United States",197.25,133.74,57.90,75.19,68.70,2.16,26.16,25.39,71.29,United States
7,8,"San Jose, CA, United States",194.75,173.72,57.44,68.83,80.85,5.89,35.75,46.48,95.53,United States
9,10,"San Diego, CA, United States",191.72,136.24,63.00,71.33,73.18,5.80,35.42,36.51,97.08,United States
10,11,"Richmond, VA, United States",191.00,116.41,57.43,73.64,68.52,3.17,20.10,31.14,81.27,United States
11,12,"Seattle, WA, United States",189.69,142.76,54.32,72.74,85.25,5.87,42.71,27.73,91.73,United States
12,13,"Portland, OR, United States",188.22,129.18,52.84,71.17,77.98,4.47,33.24,28.96,89.56,United States
13,14,"San Antonio, TX, United States",188.19,135.23,53.64,71.98,65.71,2.26,28.08,38.25,80.58,United States
15,16,"Jacksonville, FL, United States",187.31,136.36,42.33,72.56,69.04,1.99,34.46,30.85,87.81,United States
17,18,"Kansas City, MO, United States",184.19,131.32,41.08,77.26,69.01,2.16,25.65,34.39,75.08,United States
18,19,"Saint Louis, MO, United States",182.10,134.85,32.44,81.23,67.54,2.44,27.53,33.77,74.75,United States
19,20,"Sacramento, CA, United States",182.04,128.14,50.19,70.51,77.44,3.69,25.97,42.46,90.64,United States
20,21,"Boston, MA, United States",181.72,122.93,66.06,75.90,86.87,7.92,43.59,24.53,71.73,United States
21,22,"Cincinnati, OH, United States",180.74,129.22,51.18,68.50,64.97,2.31,24.52,40.93,73.24,United States
22,23,"Tampa, FL, United States",180.70,121.15,50.49,66.69,69.95,3.09,36.55,29.32,84.67,United States
23,24,"Nashville, TN, United States",180.36,140.97,53.01,62.45,68.82,2.89,37.56,39.96,83.02,United States
24,25,"Minneapolis, MN, United States",179.88,125.83,50.28,79.80,76.50,3.10,35.53,23.23,49.46,United States
25,26,"Spokane, WA, United States",178.15,107.07,48.00,62.49,73.64,3.15,24.16,20.17,67.12,United States
26,27,"Oakland, CA, United States",177.31,126.27,35.86,77.73,85.02,6.25,32.04,35.38,96.40,United States
27,28,"San Francisco, CA, United States",177.30,140.85,51.02,71.42,89.67,8.69,45.90,37.38,97.26,United States
30,31,"Pittsburgh, PA, United States",174.96,116.67,63.61,72.21,74.06,2.04,38.86,41.36,72.13,United States
32,33,"Atlanta, GA, United States",174.72,154.57,37.32,64.48,71.59,2.76,43.24,44.89,89.73,United States
34,35,"Albuquerque, NM, United States",174.24,115.89,29.95,69.11,66.73,3.12,25.77,21.62,67.06,United States
35,36,"Salt Lake City, UT, United States",174.18,138.87,73.67,71.14,64.21,3.77,34.88,61.80,66.52,United States
36,37,"Houston, TX, United States",173.57,155.10,38.76,71.69,64.65,2.04,41.45,53.70,85.53,United States
37,38,"Tucson, AZ, United States",173.44,111.07,47.98,59.63,71.54,2.63,30.38,27.12,72.66,United States
38,39,"Anchorage, AK, United States",171.27,130.57,41.12,59.85,92.69,2.61,30.95,17.96,41.61,United States
39,40,"Washington, DC, United States",170.65,137.64,43.28,69.02,90.92,4.28,41.45,40.14,81.62,United States
41,42,"Denver, CO, United States",169.01,122.12,58.56,71.48,74.59,4.81,34.73,40.25,56.28,United States
42,43,"Cleveland, OH, United States",167.97,105.92,35.31,83.06,72.71,1.41,34.48,35.59,73.11,United States
43,44,"Orlando, FL, United States",167.96,105.03,45.06,62.78,70.76,3.13,36.88,33.18,87.23,United States
45,46,"Baltimore, MD, United States",167.05,125.12,28.92,80.05,75.74,2.52,32.12,45.61,81.24,United States
46,47,"Honolulu, HI, United States",165.80,101.44,55.63,70.69,90.80,8.77,40.97,36.47,95.33,United States
48,49,"Indianapolis, IN, United States",164.66,113.29,43.27,68.80,68.33,2.33,30.83,42.82,69.92,United States
49,50,"Las Vegas, NV, United States",163.60,142.80,45.04,55.26,68.35,2.50,27.54,51.27,57.40,United States
50,51,"Phoenix, AZ, United States",159.29,139.11,47.06,66.01,66.80,2.87,32.19,57.85,53.76,United States
51,52,"Chicago, IL, United States",158.15,130.96,35.30,68.48,79.39,3.60,40.86,44.02,66.11,United States
52,53,"Los Angeles, CA, United States",157.97,123.33,59.31,66.24,77.66,7.26,47.36,60.96,95.50,United States
53,54,"Milwaukee, WI, United States",155.87,98.77,34.41,65.62,70.94,3.19,30.67,32.68,60.96,United States
54,55,"Miami, FL, United States",153.42,92.96,48.00,63.85,78.11,5.47,43.07,40.59,85.69,United States
55,56,"Philadelphia, PA, United States",151.11,100.77,40.49,72.25,85.28,3.61,40.38,48.01,77.98,United States
59,60,"New York, NY, United States",141.03,100.00,57.64,63.95,100.00,11.05,43.26,55.88,79.66,United States
60,61,"Detroit, MI, United States",130.08,90.15,28.06,65.44,64.70,1.67,47.35,54.56,66.03,United States

In [9]:
#Split City, State, Country by Comma
quality_City = quality_US.copy()
quality_City[['Metro','State','Country']] = quality_City.City.str.split(', ',expand=True).copy()
quality_City

,Rank,City,Quality of Life Index,Purchasing Power Index,Safety Index,Health Care Index,Cost of Living Index,Property Price to Income Ratio,Traffic Commute Time Index,Pollution Index,Climate Index,Country,Metro,State
0,1,"Raleigh, NC, United States",231.41,189.67,70.73,78.10,72.77,2.03,33.87,19.17,83.88,United States,Raleigh,NC
1,2,"Madison, WI, United States",207.65,135.21,72.77,81.94,65.44,3.22,23.73,16.77,51.64,United States,Madison,WI
2,3,"Dallas, TX, United States",201.17,185.61,51.39,67.63,66.75,1.98,35.30,40.20,81.85,United States,Dallas,TX
3,4,"Charlotte, NC, United States",199.48,148.02,56.62,75.66,77.14,2.26,38.27,25.82,84.05,United States,Charlotte,NC
4,5,"Austin, TX, United States",198.47,155.55,65.05,70.89,69.91,3.77,34.54,35.93,82.08,United States,Austin,TX
5,6,"Columbus, OH, United States",197.25,133.74,57.90,75.19,68.70,2.16,26.16,25.39,71.29,United States,Columbus,OH
7,8,"San Jose, CA, United States",194.75,173.72,57.44,68.83,80.85,5.89,35.75,46.48,95.53,United States,San Jose,CA
9,10,"San Diego, CA, United States",191.72,136.24,63.00,71.33,73.18,5.80,35.42,36.51,97.08,United States,San Diego,CA
10,11,"Richmond, VA, United States",191.00,116.41,57.43,73.64,68.52,3.17,20.10,31.14,81.27,United States,Richmond,VA
11,12,"Seattle, WA, United States",189.69,142.76,54.32,72.74,85.25,5.87,42.71,27.73,91.73,United States,Seattle,WA
12,13,"Portland, OR, United States",188.22,129.18,52.84,71.17,77.98,4.47,33.24,28.96,89.56,United States,Portland,OR
13,14,"San Antonio, TX, United States",188.19,135.23,53.64,71.98,65.71,2.26,28.08,38.25,80.58,United States,San Antonio,TX
15,16,"Jacksonville, FL, United States",187.31,136.36,42.33,72.56,69.04,1.99,34.46,30.85,87.81,United States,Jacksonville,FL
17,18,"Kansas City, MO, United States",184.19,131.32,41.08,77.26,69.01,2.16,25.65,34.39,75.08,United States,Kansas City,MO
18,19,"Saint Louis, MO, United States",182.10,134.85,32.44,81.23,67.54,2.44,27.53,33.77,74.75,United States,Saint Louis,MO
19,20,"Sacramento, CA, United States",182.04,128.14,50.19,70.51,77.44,3.69,25.97,42.46,90.64,United States,Sacramento,CA
20,21,"Boston, MA, United States",181.72,122.93,66.06,75.90,86.87,7.92,43.59,24.53,71.73,United States,Boston,MA
21,22,"Cincinnati, OH, United States",180.74,129.22,51.18,68.50,64.97,2.31,24.52,40.93,73.24,United States,Cincinnati,OH
22,23,"Tampa, FL, United States",180.70,121.15,50.49,66.69,69.95,3.09,36.55,29.32,84.67,United States,Tampa,FL
23,24,"Nashville, TN, United States",180.36,140.97,53.01,62.45,68.82,2.89,37.56,39.96,83.02,United States,Nashville,TN
24,25,"Minneapolis, MN, United States",179.88,125.83,50.28,79.80,76.50,3.10,35.53,23.23,49.46,United States,Minneapolis,MN
25,26,"Spokane, WA, United States",178.15,107.07,48.00,62.49,73.64,3.15,24.16,20.17,67.12,United States,Spokane,WA
26,27,"Oakland, CA, United States",177.31,126.27,35.86,77.73,85.02,6.25,32.04,35.38,96.40,United States,Oakland,CA
27,28,"San Francisco, CA, United States",177.30,140.85,51.02,71.42,89.67,8.69,45.90,37.38,97.26,United States,San Francisco,CA
30,31,"Pittsburgh, PA, United States",174.96,116.67,63.61,72.21,74.06,2.04,38.86,41.36,72.13,United States,Pittsburgh,PA
32,33,"Atlanta, GA, United States",174.72,154.57,37.32,64.48,71.59,2.76,43.24,44.89,89.73,United States,Atlanta,GA
34,35,"Albuquerque, NM, United States",174.24,115.89,29.95,69.11,66.73,3.12,25.77,21.62,67.06,United States,Albuquerque,NM
35,36,"Salt Lake City, UT, United States",174.18,138.87,73.67,71.14,64.21,3.77,34.88,61.80,66.52,United States,Salt Lake City,UT
36,37,"Houston, TX, United States",173.57,155.10,38.76,71.69,64.65,2.04,41.45,53.70,85.53,United States,Houston,TX
37,38,"Tucson, AZ, United States",173.44,111.07,47.98,59.63,71.54,2.63,30.38,27.12,72.66,United States,Tucson,AZ
38,39,"Anchorage, AK, United States",171.27,130.57,41.12,59.85,92.69,2.61,30.95,17.96,41.61,United States,Anchorage,AK
39,40,"Washington, DC, United States",170.65,137.64,43.28,69.02,90.92,4.28,41.45,40.14,81.62,United States,Washington,DC
41,42,"Denver, CO, United States",169.01,122.12,58.56,71.48,74.59,4.81,34.73,40.25,56.28,United States,Denver,CO
42,43,"Cleveland, OH, United States",167.97,105.92,35.31,83.06,72.71,1.41,34.48,35.59,73.11,United States,Cleveland,OH
43,44,"Orlando, FL, United States",167.96,105.03,45.06,62.78,70.76,3.13,36.88,33.18,87.23,United States,Orlando,FL
45,46,"Baltimore, MD, United States",167.05,125.12,28.92,80.05,75.74,2.52,32.12,45.61,81.24,United States,Baltimore,MD
46,47,"Honolulu, HI, United States",165.80,101.44,55.63,70.69,90.80,8.77,40.97,36.47,95.33,United States,Honolulu,HI
48,49,"Indianapolis, IN, United States",164.66,113.29,43.27,68.80,68.33,2.33,30.83,42.82,69.92,United States,Indianapolis,IN
49,50,"Las Vegas, NV, United States",163.60,142.80,45.04,55.26,68.35,2.50,27.54,51.27,57.40,United States,Las Vegas,NV
50,51,"Phoenix, AZ, United States",159.29,139.11,47.06,66.01,66.80,2.87,32.19,57.85,53.76,United States,Phoenix,AZ
51,52,"Chicago, IL, United States",158.15,130.96,35.30,68.48,79.39,3.60,40.86,44.02,66.11,United States,Chicago,IL
52,53,"Los Angeles, CA, United States",157.97,123.33,59.31,66.24,77.66,7.26,47.36,60.96,95.50,United States,Los Angeles,CA
53,54,"Milwaukee, WI, United States",155.87,98.77,34.41,65.62,70.94,3.19,30.67,32.68,60.96,United States,Milwaukee,WI
54,55,"Miami, FL, United States",153.42,92.96,48.00,63.85,78.11,5.47,43.07,40.59,85.69,United States,Miami,FL
55,56,"Philadelphia, PA, United States",151.11,100.77,40.49,72.25,85.28,3.61,40.38,48.01,77.98,United States,Philadelphia,PA
59,60,"New York, NY, United States",141.03,100.00,57.64,63.95,100.00,11.05,43.26,55.88,79.66,United States,New York,NY
60,61,"Detroit, MI, United States",130.08,90.15,28.06,65.44,64.70,1.67,47.35,54.56,66.03,United States,Detroit,MI

In [10]:
#Re-Rank City - find # of row
len(quality_City['Metro'])

47

In [11]:
# populate rank for Only Cities in US starting with 1
quality_City['Rank'] = [x for x in range(1,len(quality_City)+1)]
quality_City

,Rank,City,Quality of Life Index,Purchasing Power Index,Safety Index,Health Care Index,Cost of Living Index,Property Price to Income Ratio,Traffic Commute Time Index,Pollution Index,Climate Index,Country,Metro,State
0,1,"Raleigh, NC, United States",231.41,189.67,70.73,78.10,72.77,2.03,33.87,19.17,83.88,United States,Raleigh,NC
1,2,"Madison, WI, United States",207.65,135.21,72.77,81.94,65.44,3.22,23.73,16.77,51.64,United States,Madison,WI
2,3,"Dallas, TX, United States",201.17,185.61,51.39,67.63,66.75,1.98,35.30,40.20,81.85,United States,Dallas,TX
3,4,"Charlotte, NC, United States",199.48,148.02,56.62,75.66,77.14,2.26,38.27,25.82,84.05,United States,Charlotte,NC
4,5,"Austin, TX, United States",198.47,155.55,65.05,70.89,69.91,3.77,34.54,35.93,82.08,United States,Austin,TX
5,6,"Columbus, OH, United States",197.25,133.74,57.90,75.19,68.70,2.16,26.16,25.39,71.29,United States,Columbus,OH
7,7,"San Jose, CA, United States",194.75,173.72,57.44,68.83,80.85,5.89,35.75,46.48,95.53,United States,San Jose,CA
9,8,"San Diego, CA, United States",191.72,136.24,63.00,71.33,73.18,5.80,35.42,36.51,97.08,United States,San Diego,CA
10,9,"Richmond, VA, United States",191.00,116.41,57.43,73.64,68.52,3.17,20.10,31.14,81.27,United States,Richmond,VA
11,10,"Seattle, WA, United States",189.69,142.76,54.32,72.74,85.25,5.87,42.71,27.73,91.73,United States,Seattle,WA
12,11,"Portland, OR, United States",188.22,129.18,52.84,71.17,77.98,4.47,33.24,28.96,89.56,United States,Portland,OR
13,12,"San Antonio, TX, United States",188.19,135.23,53.64,71.98,65.71,2.26,28.08,38.25,80.58,United States,San Antonio,TX
15,13,"Jacksonville, FL, United States",187.31,136.36,42.33,72.56,69.04,1.99,34.46,30.85,87.81,United States,Jacksonville,FL
17,14,"Kansas City, MO, United States",184.19,131.32,41.08,77.26,69.01,2.16,25.65,34.39,75.08,United States,Kansas City,MO
18,15,"Saint Louis, MO, United States",182.10,134.85,32.44,81.23,67.54,2.44,27.53,33.77,74.75,United States,Saint Louis,MO
19,16,"Sacramento, CA, United States",182.04,128.14,50.19,70.51,77.44,3.69,25.97,42.46,90.64,United States,Sacramento,CA
20,17,"Boston, MA, United States",181.72,122.93,66.06,75.90,86.87,7.92,43.59,24.53,71.73,United States,Boston,MA
21,18,"Cincinnati, OH, United States",180.74,129.22,51.18,68.50,64.97,2.31,24.52,40.93,73.24,United States,Cincinnati,OH
22,19,"Tampa, FL, United States",180.70,121.15,50.49,66.69,69.95,3.09,36.55,29.32,84.67,United States,Tampa,FL
23,20,"Nashville, TN, United States",180.36,140.97,53.01,62.45,68.82,2.89,37.56,39.96,83.02,United States,Nashville,TN
24,21,"Minneapolis, MN, United States",179.88,125.83,50.28,79.80,76.50,3.10,35.53,23.23,49.46,United States,Minneapolis,MN
25,22,"Spokane, WA, United States",178.15,107.07,48.00,62.49,73.64,3.15,24.16,20.17,67.12,United States,Spokane,WA
26,23,"Oakland, CA, United States",177.31,126.27,35.86,77.73,85.02,6.25,32.04,35.38,96.40,United States,Oakland,CA
27,24,"San Francisco, CA, United States",177.30,140.85,51.02,71.42,89.67,8.69,45.90,37.38,97.26,United States,San Francisco,CA
30,25,"Pittsburgh, PA, United States",174.96,116.67,63.61,72.21,74.06,2.04,38.86,41.36,72.13,United States,Pittsburgh,PA
32,26,"Atlanta, GA, United States",174.72,154.57,37.32,64.48,71.59,2.76,43.24,44.89,89.73,United States,Atlanta,GA
34,27,"Albuquerque, NM, United States",174.24,115.89,29.95,69.11,66.73,3.12,25.77,21.62,67.06,United States,Albuquerque,NM
35,28,"Salt Lake City, UT, United States",174.18,138.87,73.67,71.14,64.21,3.77,34.88,61.80,66.52,United States,Salt Lake City,UT
36,29,"Houston, TX, United States",173.57,155.10,38.76,71.69,64.65,2.04,41.45,53.70,85.53,United States,Houston,TX
37,30,"Tucson, AZ, United States",173.44,111.07,47.98,59.63,71.54,2.63,30.38,27.12,72.66,United States,Tucson,AZ
38,31,"Anchorage, AK, United States",171.27,130.57,41.12,59.85,92.69,2.61,30.95,17.96,41.61,United States,Anchorage,AK
39,32,"Washington, DC, United States",170.65,137.64,43.28,69.02,90.92,4.28,41.45,40.14,81.62,United States,Washington,DC
41,33,"Denver, CO, United States",169.01,122.12,58.56,71.48,74.59,4.81,34.73,40.25,56.28,United States,Denver,CO
42,34,"Cleveland, OH, United States",167.97,105.92,35.31,83.06,72.71,1.41,34.48,35.59,73.11,United States,Cleveland,OH
43,35,"Orlando, FL, United States",167.96,105.03,45.06,62.78,70.76,3.13,36.88,33.18,87.23,United States,Orlando,FL
45,36,"Baltimore, MD, United States",167.05,125.12,28.92,80.05,75.74,2.52,32.12,45.61,81.24,United States,Baltimore,MD
46,37,"Honolulu, HI, United States",165.80,101.44,55.63,70.69,90.80,8.77,40.97,36.47,95.33,United States,Honolulu,HI
48,38,"Indianapolis, IN, United States",164.66,113.29,43.27,68.80,68.33,2.33,30.83,42.82,69.92,United States,Indianapolis,IN
49,39,"Las Vegas, NV, United States",163.60,142.80,45.04,55.26,68.35,2.50,27.54,51.27,57.40,United States,Las Vegas,NV
50,40,"Phoenix, AZ, United States",159.29,139.11,47.06,66.01,66.80,2.87,32.19,57.85,53.76,United States,Phoenix,AZ
51,41,"Chicago, IL, United States",158.15,130.96,35.30,68.48,79.39,3.60,40.86,44.02,66.11,United States,Chicago,IL
52,42,"Los Angeles, CA, United States",157.97,123.33,59.31,66.24,77.66,7.26,47.36,60.96,95.50,United States,Los Angeles,CA
53,43,"Milwaukee, WI, United States",155.87,98.77,34.41,65.62,70.94,3.19,30.67,32.68,60.96,United States,Milwaukee,WI
54,44,"Miami, FL, United States",153.42,92.96,48.00,63.85,78.11,5.47,43.07,40.59,85.69,United States,Miami,FL
55,45,"Philadelphia, PA, United States",151.11,100.77,40.49,72.25,85.28,3.61,40.38,48.01,77.98,United States,Philadelphia,PA
59,46,"New York, NY, United States",141.03,100.00,57.64,63.95,100.00,11.05,43.26,55.88,79.66,United States,New York,NY
60,47,"Detroit, MI, United States",130.08,90.15,28.06,65.44,64.70,1.67,47.35,54.56,66.03,United States,Detroit,MI

In [12]:
#Scrape state acroynym table
stateurl='https://www.factmonster.com/us/postal-information/state-abbreviations-and-state-postal-codes'
#scrape and read as pandas df
scrapeState = pd.read_html(stateurl,header=0)

In [13]:
#convert to df object
state_df = scrapeState[0]
state_df.head()

            State Abbreviation Postalcode
0         Alabama         Ala.         AL
1          Alaska       Alaska         AK
2  American Samoa          NaN         AS
3         Arizona        Ariz.         AZ
4        Arkansas         Ark.         AR

In [14]:
#Rename state_df columns to set join with quality_City
state_name_df = state_df.rename(columns={'State':'State_Long','Postalcode':'State'})
state_name_df.tail(10)

        State_Long Abbreviation State
49       Tennessee        Tenn.    TN
50           Texas         Tex.    TX
51            Utah         Utah    UT
52         Vermont          Vt.    VT
53        Virginia          Va.    VA
54  Virgin Islands         V.I.    VI
55      Washington        Wash.    WA
56   West Virginia        W.Va.    WV
57       Wisconsin         Wis.    WI
58         Wyoming         Wyo.    WY

In [15]:
quality_City['State'].unique()

array(['NC', 'WI', 'TX', 'OH', 'CA', 'VA', 'WA', 'OR', 'FL', 'MO', 'MA',
       'TN', 'MN', 'PA', 'GA', 'NM', 'UT', 'AZ', 'AK', 'DC', 'CO', 'MD',
       'HI', 'IN', 'NV', 'IL', 'NY', 'MI'], dtype=object)

In [16]:
state_name_df['State'].unique()

array(['AL', 'AK', 'AS', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL',
       'GA', 'GU', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME',
       'MD', 'MH', 'MA', 'MI', 'FM', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV',
       'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'MP', 'OH', 'OK', 'OR', 'PW',
       'PA', 'PR', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'VI',
       'WA', 'WV', 'WI', 'WY'], dtype=object)

In [17]:
state_name_df['State_Long'].unique()

array(['Alabama', 'Alaska', 'American Samoa', 'Arizona', 'Arkansas',
       'California', 'Colorado', 'Connecticut', 'Delaware',
       'Dist. of Columbia', 'Florida', 'Georgia', 'Guam', 'Hawaii',
       'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky',
       'Louisiana', 'Maine', 'Maryland', 'Marshall Islands',
       'Massachusetts', 'Michigan', 'Micronesia', 'Minnesota',
       'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
       'New Hampshire', 'New Jersey', 'New Mexico', 'New York',
       'North Carolina', 'North Dakota', 'Northern Marianas', 'Ohio',
       'Oklahoma', 'Oregon', 'Palau', 'Pennsylvania', 'Puerto Rico',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Virgin Islands',
       'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'],
      dtype=object)

In [18]:
# Join the long State Name to Quality City 
quality_Index = quality_City.merge(state_name_df, on='State', how='left')
quality_Index

,Rank,City,Quality of Life Index,Purchasing Power Index,Safety Index,Health Care Index,Cost of Living Index,Property Price to Income Ratio,Traffic Commute Time Index,Pollution Index,Climate Index,Country,Metro,State,State_Long,Abbreviation
0,1,"Raleigh, NC, United States",231.41,189.67,70.73,78.10,72.77,2.03,33.87,19.17,83.88,United States,Raleigh,NC,North Carolina,N.C.
1,2,"Madison, WI, United States",207.65,135.21,72.77,81.94,65.44,3.22,23.73,16.77,51.64,United States,Madison,WI,Wisconsin,Wis.
2,3,"Dallas, TX, United States",201.17,185.61,51.39,67.63,66.75,1.98,35.30,40.20,81.85,United States,Dallas,TX,Texas,Tex.
3,4,"Charlotte, NC, United States",199.48,148.02,56.62,75.66,77.14,2.26,38.27,25.82,84.05,United States,Charlotte,NC,North Carolina,N.C.
4,5,"Austin, TX, United States",198.47,155.55,65.05,70.89,69.91,3.77,34.54,35.93,82.08,United States,Austin,TX,Texas,Tex.
5,6,"Columbus, OH, United States",197.25,133.74,57.90,75.19,68.70,2.16,26.16,25.39,71.29,United States,Columbus,OH,Ohio,Ohio
6,7,"San Jose, CA, United States",194.75,173.72,57.44,68.83,80.85,5.89,35.75,46.48,95.53,United States,San Jose,CA,California,Calif.
7,8,"San Diego, CA, United States",191.72,136.24,63.00,71.33,73.18,5.80,35.42,36.51,97.08,United States,San Diego,CA,California,Calif.
8,9,"Richmond, VA, United States",191.00,116.41,57.43,73.64,68.52,3.17,20.10,31.14,81.27,United States,Richmond,VA,Virginia,Va.
9,10,"Seattle, WA, United States",189.69,142.76,54.32,72.74,85.25,5.87,42.71,27.73,91.73,United States,Seattle,WA,Washington,Wash.
10,11,"Portland, OR, United States",188.22,129.18,52.84,71.17,77.98,4.47,33.24,28.96,89.56,United States,Portland,OR,Oregon,Ore.
11,12,"San Antonio, TX, United States",188.19,135.23,53.64,71.98,65.71,2.26,28.08,38.25,80.58,United States,San Antonio,TX,Texas,Tex.
12,13,"Jacksonville, FL, United States",187.31,136.36,42.33,72.56,69.04,1.99,34.46,30.85,87.81,United States,Jacksonville,FL,Florida,Fla.
13,14,"Kansas City, MO, United States",184.19,131.32,41.08,77.26,69.01,2.16,25.65,34.39,75.08,United States,Kansas City,MO,Missouri,Mo.
14,15,"Saint Louis, MO, United States",182.10,134.85,32.44,81.23,67.54,2.44,27.53,33.77,74.75,United States,Saint Louis,MO,Missouri,Mo.
15,16,"Sacramento, CA, United States",182.04,128.14,50.19,70.51,77.44,3.69,25.97,42.46,90.64,United States,Sacramento,CA,California,Calif.
16,17,"Boston, MA, United States",181.72,122.93,66.06,75.90,86.87,7.92,43.59,24.53,71.73,United States,Boston,MA,Massachusetts,Mass.
17,18,"Cincinnati, OH, United States",180.74,129.22,51.18,68.50,64.97,2.31,24.52,40.93,73.24,United States,Cincinnati,OH,Ohio,Ohio
18,19,"Tampa, FL, United States",180.70,121.15,50.49,66.69,69.95,3.09,36.55,29.32,84.67,United States,Tampa,FL,Florida,Fla.
19,20,"Nashville, TN, United States",180.36,140.97,53.01,62.45,68.82,2.89,37.56,39.96,83.02,United States,Nashville,TN,Tennessee,Tenn.
20,21,"Minneapolis, MN, United States",179.88,125.83,50.28,79.80,76.50,3.10,35.53,23.23,49.46,United States,Minneapolis,MN,Minnesota,Minn.
21,22,"Spokane, WA, United States",178.15,107.07,48.00,62.49,73.64,3.15,24.16,20.17,67.12,United States,Spokane,WA,Washington,Wash.
22,23,"Oakland, CA, United States",177.31,126.27,35.86,77.73,85.02,6.25,32.04,35.38,96.40,United States,Oakland,CA,California,Calif.
23,24,"San Francisco, CA, United States",177.30,140.85,51.02,71.42,89.67,8.69,45.90,37.38,97.26,United States,San Francisco,CA,California,Calif.
24,25,"Pittsburgh, PA, United States",174.96,116.67,63.61,72.21,74.06,2.04,38.86,41.36,72.13,United States,Pittsburgh,PA,Pennsylvania,Pa.
25,26,"Atlanta, GA, United States",174.72,154.57,37.32,64.48,71.59,2.76,43.24,44.89,89.73,United States,Atlanta,GA,Georgia,Ga.
26,27,"Albuquerque, NM, United States",174.24,115.89,29.95,69.11,66.73,3.12,25.77,21.62,67.06,United States,Albuquerque,NM,New Mexico,N.M.
27,28,"Salt Lake City, UT, United States",174.18,138.87,73.67,71.14,64.21,3.77,34.88,61.80,66.52,United States,Salt Lake City,UT,Utah,Utah
28,29,"Houston, TX, United States",173.57,155.10,38.76,71.69,64.65,2.04,41.45,53.70,85.53,United States,Houston,TX,Texas,Tex.
29,30,"Tucson, AZ, United States",173.44,111.07,47.98,59.63,71.54,2.63,30.38,27.12,72.66,United States,Tucson,AZ,Arizona,Ariz.
30,31,"Anchorage, AK, United States",171.27,130.57,41.12,59.85,92.69,2.61,30.95,17.96,41.61,United States,Anchorage,AK,Alaska,Alaska
31,32,"Washington, DC, United States",170.65,137.64,43.28,69.02,90.92,4.28,41.45,40.14,81.62,United States,Washington,DC,Dist. of Columbia,D.C.
32,33,"Denver, CO, United States",169.01,122.12,58.56,71.48,74.59,4.81,34.73,40.25,56.28,United States,Denver,CO,Colorado,Colo.
33,34,"Cleveland, OH, United States",167.97,105.92,35.31,83.06,72.71,1.41,34.48,35.59,73.11,United States,Cleveland,OH,Ohio,Ohio
34,35,"Orlando, FL, United States",167.96,105.03,45.06,62.78,70.76,3.13,36.88,33.18,87.23,United States,Orlando,FL,Florida,Fla.
35,36,"Baltimore, MD, United States",167.05,125.12,28.92,80.05,75.74,2.52,32.12,45.61,81.24,United States,Baltimore,MD,Maryland,Md.
36,37,"Honolulu, HI, United States",165.80,101.44,55.63,70.69,90.80,8.77,40.97,36.47,95.33,United States,Honolulu,HI,Hawaii,Hawaii
37,38,"Indianapolis, IN, United States",164.66,113.29,43.27,68.80,68.33,2.33,30.83,42.82,69.92,United States,Indianapolis,IN,Indiana,Ind.
38,39,"Las Vegas, NV, United States",163.60,142.80,45.04,55.26,68.35,2.50,27.54,51.27,57.40,United States,Las Vegas,NV,Nevada,Nev.
39,40,"Phoenix, AZ, United States",159.29,139.11,47.06,66.01,66.80,2.87,32.19,57.85,53.76,United States,Phoenix,AZ,Arizona,Ariz.
40,41,"Chicago, IL, United States",158.15,130.96,35.30,68.48,79.39,3.60,40.86,44.02,66.11,United States,Chicago,IL,Illinois,Ill.
41,42,"Los Angeles, CA, United States",157.97,123.33,59.31,66.24,77.66,7.26,47.36,60.96,95.50,United States,Los Angeles,CA,California,Calif.
42,43,"Milwaukee, WI, United States",155.87,98.77,34.41,65.62,70.94,3.19,30.67,32.68,60.96,United States,Milwaukee,WI,Wisconsin,Wis.
43,44,"Miami, FL, United States",153.42,92.96,48.00,63.85,78.11,5.47,43.07,40.59,85.69,United States,Miami,FL,Florida,Fla.
44,45,"Philadelphia, PA, United States",151.11,100.77,40.49,72.25,85.28,3.61,40.38,48.01,77.98,United States,Philadelphia,PA,Pennsylvania,Pa.
45,46,"New York, NY, United States",141.03,100.00,57.64,63.95,100.00,11.05,43.26,55.88,79.66,United States,New York,NY,New York,N.Y.
46,47,"Detroit, MI, United States",130.08,90.15,28.06,65.44,64.70,1.67,47.35,54.56,66.03,United States,Detroit,MI,Michigan,Mich.

In [19]:
#check columns
quality_Index.columns

Index(['Rank', 'City', 'Quality of Life Index', 'Purchasing Power Index',
       'Safety Index', 'Health Care Index', 'Cost of Living Index',
       'Property Price to Income Ratio', 'Traffic Commute Time Index',
       'Pollution Index', 'Climate Index', 'Country', 'Metro', 'State',
       'State_Long', 'Abbreviation'],
      dtype='object')

In [20]:
#Rename Columns to Export into MySQL
quality_final = quality_Index.rename(columns={'Quality of Life Index':'QOL_Index',
                             'Purchasing Power Index':'PP_Index',
                             'Safety Index':'Safety_Index',
                             'Health Care Index':'Health_Index',
                             'Cost of Living Index': 'CL_Index',
                             'Property Price to Income Ratio':'PPIR_Index',
                             'Traffic Commute Time Index':'TCT_Index',
                             'Pollution Index':'Pollution_Index',
                             'Climate Index':'Climate_Index'})

In [21]:
#check columns
quality_final.columns

Index(['Rank', 'City', 'QOL_Index', 'PP_Index', 'Safety_Index', 'Health_Index',
       'CL_Index', 'PPIR_Index', 'TCT_Index', 'Pollution_Index',
       'Climate_Index', 'Country', 'Metro', 'State', 'State_Long',
       'Abbreviation'],
      dtype='object')

In [22]:
# connect to local db
from sqlalchemy import create_engine
rds_connection_string = f"root:{password}@127.0.0.1/Quality_db"
engine = create_engine(f'mysql://{rds_connection_string}')

In [24]:
quality_final.to_sql(name='quality_final', con=engine, if_exists='append', index=False)

In [25]:
pd.read_sql_query('select * from quality_final', con=engine).head()

,Rank,City,QOL_Index,PP_Index,Safety_Index,Health_Index,CL_Index,PPIR_Index,TCT_Index,Pollution_Index,Climate_Index,Country,Metro,State,State_Long,Abbreviation
0,1,"Raleigh, NC, United States",231.41,189.67,70.73,78.10,72.77,2.03,33.87,19.17,83.88,United States,Raleigh,NC,North Carolina,N.C.
1,2,"Madison, WI, United States",207.65,135.21,72.77,81.94,65.44,3.22,23.73,16.77,51.64,United States,Madison,WI,Wisconsin,Wis.
2,3,"Dallas, TX, United States",201.17,185.61,51.39,67.63,66.75,1.98,35.30,40.20,81.85,United States,Dallas,TX,Texas,Tex.
3,4,"Charlotte, NC, United States",199.48,148.02,56.62,75.66,77.14,2.26,38.27,25.82,84.05,United States,Charlotte,NC,North Carolina,N.C.
4,5,"Austin, TX, United States",198.47,155.55,65.05,70.89,69.91,3.77,34.54,35.93,82.08,United States,Austin,TX,Texas,Tex.